/**
 * Shared error codes used across the OpusAIMobility consolidated platform.
 * Both TerraAI PHP API and OpusAIMobility Node.js backend use these codes.
 */

export const ERROR_CODES = {
  // Authentication errors
  AUTH_CREDENTIALS_REQUIRED: 'AUTH_CREDENTIALS_REQUIRED',
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_INSUFFICIENT_PERMISSIONS: 'AUTH_INSUFFICIENT_PERMISSIONS',

  // Database errors
  DB_CONNECTIVITY_FAILURE: 'DB_CONNECTIVITY_FAILURE',
  DB_CONSTRAINT_VIOLATION: 'DB_CONSTRAINT_VIOLATION',
  DB_TYPE_MISMATCH: 'DB_TYPE_MISMATCH',

  // File errors
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  FILE_UPLOAD_FAILED: 'FILE_UPLOAD_FAILED',

  // Gateway errors
  GATEWAY_TIMEOUT: 'GATEWAY_TIMEOUT',
  PATH_NOT_FOUND: 'PATH_NOT_FOUND',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',

  // Migration errors
  MIGRATION_EXPORT_FAILED: 'MIGRATION_EXPORT_FAILED',
  MIGRATION_IMPORT_HALTED: 'MIGRATION_IMPORT_HALTED',
  MIGRATION_SNAPSHOT_FAILED: 'MIGRATION_SNAPSHOT_FAILED',
  MIGRATION_VERIFICATION_FAILED: 'MIGRATION_VERIFICATION_FAILED',

  // Notification errors
  NOTIFICATION_DELIVERY_FAILED: 'NOTIFICATION_DELIVERY_FAILED',
  NOTIFICATION_ENDPOINT_DISABLED: 'NOTIFICATION_ENDPOINT_DISABLED',
  NOTIFICATION_TOKEN_INVALID: 'NOTIFICATION_TOKEN_INVALID',

  // General
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
