/**
 * HTTP status codes and their mappings to error codes used across the platform.
 */

import type { ErrorCode } from './error-codes.js';
import { ERROR_CODES } from './error-codes.js';

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,

  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  PAYLOAD_TOO_LARGE: 413,

  INTERNAL_SERVER_ERROR: 500,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504,
} as const;

export type HttpStatusCode = (typeof HTTP_STATUS)[keyof typeof HTTP_STATUS];

/**
 * Maps error codes to their corresponding HTTP status codes.
 */
export const ERROR_CODE_TO_HTTP_STATUS: Record<ErrorCode, number> = {
  [ERROR_CODES.AUTH_CREDENTIALS_REQUIRED]: HTTP_STATUS.UNAUTHORIZED,
  [ERROR_CODES.AUTH_INVALID_TOKEN]: HTTP_STATUS.UNAUTHORIZED,
  [ERROR_CODES.AUTH_TOKEN_EXPIRED]: HTTP_STATUS.UNAUTHORIZED,
  [ERROR_CODES.AUTH_INSUFFICIENT_PERMISSIONS]: HTTP_STATUS.FORBIDDEN,

  [ERROR_CODES.DB_CONNECTIVITY_FAILURE]: HTTP_STATUS.SERVICE_UNAVAILABLE,
  [ERROR_CODES.DB_CONSTRAINT_VIOLATION]: HTTP_STATUS.BAD_REQUEST,
  [ERROR_CODES.DB_TYPE_MISMATCH]: HTTP_STATUS.BAD_REQUEST,

  [ERROR_CODES.FILE_TOO_LARGE]: HTTP_STATUS.PAYLOAD_TOO_LARGE,
  [ERROR_CODES.FILE_NOT_FOUND]: HTTP_STATUS.NOT_FOUND,
  [ERROR_CODES.FILE_UPLOAD_FAILED]: HTTP_STATUS.BAD_GATEWAY,

  [ERROR_CODES.GATEWAY_TIMEOUT]: HTTP_STATUS.GATEWAY_TIMEOUT,
  [ERROR_CODES.PATH_NOT_FOUND]: HTTP_STATUS.NOT_FOUND,
  [ERROR_CODES.SERVICE_UNAVAILABLE]: HTTP_STATUS.SERVICE_UNAVAILABLE,

  [ERROR_CODES.MIGRATION_EXPORT_FAILED]: HTTP_STATUS.INTERNAL_SERVER_ERROR,
  [ERROR_CODES.MIGRATION_IMPORT_HALTED]: HTTP_STATUS.INTERNAL_SERVER_ERROR,
  [ERROR_CODES.MIGRATION_SNAPSHOT_FAILED]: HTTP_STATUS.INTERNAL_SERVER_ERROR,
  [ERROR_CODES.MIGRATION_VERIFICATION_FAILED]: HTTP_STATUS.INTERNAL_SERVER_ERROR,

  [ERROR_CODES.NOTIFICATION_DELIVERY_FAILED]: HTTP_STATUS.BAD_GATEWAY,
  [ERROR_CODES.NOTIFICATION_ENDPOINT_DISABLED]: HTTP_STATUS.BAD_REQUEST,
  [ERROR_CODES.NOTIFICATION_TOKEN_INVALID]: HTTP_STATUS.BAD_REQUEST,

  [ERROR_CODES.INTERNAL_ERROR]: HTTP_STATUS.INTERNAL_SERVER_ERROR,
  [ERROR_CODES.VALIDATION_ERROR]: HTTP_STATUS.BAD_REQUEST,
};

/**
 * Returns the human-readable error message for a given error code.
 */
export const ERROR_MESSAGES: Record<ErrorCode, string> = {
  [ERROR_CODES.AUTH_CREDENTIALS_REQUIRED]: 'Authentication credentials required',
  [ERROR_CODES.AUTH_INVALID_TOKEN]: 'Invalid token format',
  [ERROR_CODES.AUTH_TOKEN_EXPIRED]: 'Token expired',
  [ERROR_CODES.AUTH_INSUFFICIENT_PERMISSIONS]: 'Insufficient permissions',

  [ERROR_CODES.DB_CONNECTIVITY_FAILURE]: 'Database connectivity failure',
  [ERROR_CODES.DB_CONSTRAINT_VIOLATION]: 'Database constraint violation',
  [ERROR_CODES.DB_TYPE_MISMATCH]: 'Data type mismatch',

  [ERROR_CODES.FILE_TOO_LARGE]: 'File too large',
  [ERROR_CODES.FILE_NOT_FOUND]: 'File not found',
  [ERROR_CODES.FILE_UPLOAD_FAILED]: 'File upload could not be completed',

  [ERROR_CODES.GATEWAY_TIMEOUT]: 'Gateway timeout',
  [ERROR_CODES.PATH_NOT_FOUND]: 'Path not found',
  [ERROR_CODES.SERVICE_UNAVAILABLE]: 'Service unavailable',

  [ERROR_CODES.MIGRATION_EXPORT_FAILED]: 'Database export failed',
  [ERROR_CODES.MIGRATION_IMPORT_HALTED]: 'Database import halted due to errors',
  [ERROR_CODES.MIGRATION_SNAPSHOT_FAILED]: 'Pre-migration snapshot creation failed',
  [ERROR_CODES.MIGRATION_VERIFICATION_FAILED]: 'Migration verification failed',

  [ERROR_CODES.NOTIFICATION_DELIVERY_FAILED]: 'Notification delivery failed',
  [ERROR_CODES.NOTIFICATION_ENDPOINT_DISABLED]: 'Notification endpoint is disabled',
  [ERROR_CODES.NOTIFICATION_TOKEN_INVALID]: 'Invalid notification token',

  [ERROR_CODES.INTERNAL_ERROR]: 'Internal server error',
  [ERROR_CODES.VALIDATION_ERROR]: 'Validation error',
};
